


class HomePage:

    header1 = '//h1'
    header2 = '//h2'

    ab_testing = '//a[text()="A/B Testing"]'
    add_remove_elements = '//a[text()="Add/Remove Elements"]'
    basic_auth = '//a[text()="Basic Auth"]'
    broken_images = '//a[text()="Broken Images"]'
    challenging_dom = '//a[text()="Challenging DOM"]'
    checkboxes = '//a[text()="Checkboxes"]'
    context_menu = '//a[text()="Context Menu"]'
    digest_authentication = '//a[text()="Digest Authentication"]'
    disappearing_elements = '//a[text()="Disappearing Elements"]'
    drag_and_drop = '//a[text()="Drag and Drop"]'
    dropdown = '//a[text()="Dropdown"]'
    dynamic_content = '//a[text()="Dynamic Content"]'
    dynamic_controls = '//a[text()="Dynamic Controls"]'
    dynamic_loading = '//a[text()="Dynamic Loading"]'
    entry_ad = '//a[text()="Entry Ad"]'
    exit_intent = '//a[text()="Exit Intent"]'
    file_download = '//a[text()="File Download"]'
    file_upload = '//a[text()="File Upload"]'
    floating_menu = '//a[text()="Floating Menu"]'
    forgot_password = '//a[text()="Forgot Password"]'
    form_authentication = '//a[text()="Form Authentication"]'
    frames = '//a[text()="Frames"]'
    geolocation = '//a[text()="Geolocation"]'
    horizontal_slider = '//a[text()="Horizontal Slider"]'
    hovers = '//a[text()="Hovers"]'
    infinite_scroll = '//a[text()="Infinite Scroll"]'
    inputs = '//a[text()="Inputs"]'
    jquery_ui_menus = '//a[text()="JQuery UI Menus"]'
    javascript_alerts = '//a[text()="JavaScript Alerts"]'
    javascript_onload_event_error = '//a[text()="JavaScript onload event error"]'
    key_presses = '//a[text()="Key Presses"]'
    large_and_deep_dom = '//a[text()="Large & Deep DOM"]'
    multiple_windows = '//a[text()="Multiple Windows"]'
    nested_frames = '//a[text()="Nested Frames"]'
    notification_messages = '//a[text()="Notification Messages"]'
    redirect_link = '//a[text()="Redirect Link"]'
    secure_file_download = '//a[text()="Secure File Download"]'
    shadow_dom = '//a[text()="Shadow DOM"]'
    shifting_content = '//a[text()="Shifting Content"]'
    slow_resources = '//a[text()="Slow Resources"]'
    sortable_data_tables = '//a[text()="Sortable Data Tables"]'
    status_codes = '//a[text()="Status Codes"]'
    typos = '//a[text()="Typos"]'
    wysiwyg_editor = '//a[text()="WYSIWYG Editor"]'
